//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ML.BC.EnterpriseData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enterprise
    {
        public string EnterpriseID { get; set; }
        public string Name { get; set; }
        public string ProfessionID { get; set; }
        public string PropertyID { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public byte Status { get; set; }
        public System.DateTime RegistDate { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public bool Deleted { get; set; }
    }
}
