//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ML.BC.EnterpriseData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrontUser
    {
        public string UserID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string EnterpiseID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string Mobile { get; set; }
        public System.DateTime RegistDate { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public string LastIP { get; set; }
        public bool LoginByDesktop { get; set; }
        public bool LoginByMobile { get; set; }
        public bool Closed { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string Picture { get; set; }
    }
}
