//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ML.BC.BCBackData.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BCBackContext : DbContext
    {
        public BCBackContext()
            : base("name=BCBackContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BackUser> BackUsers { get; set; }
        public virtual DbSet<RFAAuthorization> RFAAuthorizations { get; set; }
        public virtual DbSet<RFAFunction> RFAFunctions { get; set; }
        public virtual DbSet<RFARole> RFARoles { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
    }
}
