//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ML.BC.EnterpriseData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enterprise
    {
        public string EnterpriseID { get; set; }
        public string Name { get; set; }
        public string ProfessionID { get; set; }
        public string PropertyID { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public byte Status { get; set; }
        public System.DateTime RegistDate { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public bool Deleted { get; set; }
    }
}
