//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ML.BC.EnterpriseData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public string ProjectID { get; set; }
        public string Name { get; set; }
        public string EnterpriseID { get; set; }
        public string Departments { get; set; }
        public string Managers { get; set; }
        public string Roles { get; set; }
        public System.DateTime RegistDate { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public byte Status { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
