//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ML.BC.EnterpriseData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scene
    {
        public string SceneID { get; set; }
        public string Name { get; set; }
        public string EnterpriseID { get; set; }
        public string ProjectID { get; set; }
        public string ParentSceneID { get; set; }
        public string Woker { get; set; }
        public System.DateTime RegistDate { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public byte Status { get; set; }
        public bool Deleted { get; set; }
        public string Type { get; set; }
        public string Address { get; set; }
        public string LatitudeAndLongitude { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public bool HasData { get; set; }
    }
}
