//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ML.BC.EnterpriseData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginLog
    {
        public int UserLoginLogID { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string IP { get; set; }
        public System.DateTime Time { get; set; }
        public string Device { get; set; }
        public int Status { get; set; }
        public string Description { get; set; }
    }
}
