//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ML.BC.EnterpriseData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public string UserID { get; set; }
        public int RoleID { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public bool Deleted { get; set; }
    }
}
