//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ML.BC.BCBackData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackUser
    {
        public string UserID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Mobile { get; set; }
        public System.DateTime RegistDate { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public string LastIP { get; set; }
        public bool Closed { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
