//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ML.BC.BCBackData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFAFunction
    {
        public string FunctionID { get; set; }
        public string Name { get; set; }
        public string MyID { get; set; }
        public string ParentID { get; set; }
        public string Desription { get; set; }
        public bool Available { get; set; }
    }
}
